import { useEffect, useState } from 'react';
import type { Settings, Player } from '../types';
import type { CampaignBattleState } from '../campaign/types';
import {
  startBattle, addDart, undoDart, setTarget, resolvePlayerVisit,
} from '../campaign/engine';
import { getEnemyDef } from '../campaign/engine/enemies';
import { Sound } from '../sound';
import type { MusicEngine } from '../music';
import { DartOverlay } from '../campaign/DartOverlay';
import { FrozenOverlay } from '../campaign/FrozenOverlay';
import { Modal } from '../Popups';
import type { DartliteRun, ChoiceOption } from './engine';
import { isMiniBossRound, isBossRound, applyPlayerChoice, applyBossTrinketChoice } from './engine';
import { getTrinket } from './trinkets';
import { ChoiceScreen } from './ChoiceScreen';
import { ownsPlayer, type LobbyPlayer } from '../multiplayer/client';
import { DeckUpgradeScreen } from './DeckUpgradeScreen';
import { BOSS_INTRO_STORIES, MINIBOSS_INTRO_STORIES } from './bossStories';
import { ProgressScreen } from './ProgressScreen';
import { PlayerDetailModal } from './PlayerDetailModal';
import { BossVictoryScreen } from './BossVictoryScreen';
import { RewardRevealOverlay } from './RewardRevealOverlay';
import type { CardDef } from '../cards/types';
import { resolveCardDef } from '../cards/deck';
import { CardHand } from '../cards/CardHand';
import { EnemyList } from '../campaign/shared/EnemyList';
import { PlayerChips } from '../campaign/shared/PlayerChips';
import { PartyHpBar } from '../campaign/shared/PartyHpBar';
import { DartKeypad } from '../campaign/shared/DartKeypad';
import { PlayerTurnInfo } from '../campaign/shared/PlayerTurnInfo';
import { useCardBattle } from '../campaign/shared/useCardBattle';
