export const MODES: Record<string, { start: number; label: string; atc?: boolean; practice?: boolean; killer?: boolean; party?: boolean; desc: string; rules: string[] }> = {
  '501': { start: 501, label: '501',
    desc: 'The classic. Race from 501 down to zero.',
    rules: [
      'Each player starts on 501.',
      'Take turns throwing 3 darts per visit.',
      'Subtract each visit from your remaining score.',
      'First to reach exactly zero wins the leg.',
      'Optionally require a double to finish (Double Out).',
      'Best-of multiple legs decides the match.',
    ] },
  '301': { start: 301, label: '301',
    desc: 'A shorter version of 501 — faster finishes.',
    rules: [
      'Each player starts on 301.',
      'Take turns throwing 3 darts per visit.',
      'Subtract each visit from your remaining score.',
      'First to reach exactly zero wins the leg.',
      'Optionally require a double to finish (Double Out).',
      'Best-of multiple legs decides the match.',
    ] },
  '701': { start: 701, label: '701',
    desc: 'A longer format for more players or extended matches.',
    rules: [
      'Each player starts on 701.',
      'Take turns throwing 3 darts per visit.',
      'Subtract each visit from your remaining score.',
      'First to reach exactly zero wins the leg.',
      'Optionally require a double to finish (Double Out).',
      'Best-of multiple legs decides the match.',
    ] },
  '101': { start: 101, label: '101',
    desc: 'A quick sprint — one visit can win it.',
    rules: [
      'Each player starts on 101.',
      'Take turns throwing 3 darts per visit.',
      'Subtract each visit from your remaining score.',
      'First to reach exactly zero wins the leg.',
      'Optionally require a double to finish (Double Out).',
      'Best-of multiple legs decides the match.',
    ] },
  'atc': { start: 0, label: 'Around the Clock', atc: true,
    desc: 'Hit the numbers 1 through 20 and the Bull in order.',
    rules: [
      'Hit numbers 1, 2, 3 … 20, then the Bull — in sequence.',
      'Any segment (single, double, triple) counts.',
      '3 darts per visit, then play passes to the next player.',
      'First to land the Bull wins.',
      'Great for practicing the whole board.',
    ] },
  'practice': { start: 0, label: 'Practice', practice: true,
    desc: 'Free scoring — no rules, just throw.',
    rules: [
      'No target score and no checkout.',
      'Throw 3 darts per visit and watch your totals stack up.',
      'Turns rotate between players so everyone can warm up.',
      'Use it to groove your throw or test combinations.',
      'Practice games do not count toward competitive stats.',
    ] },
  'killer': { start: 0, label: 'Killer', killer: true,
    desc: 'Hit your number 5 times to become a Killer, then knock out opponents by hitting their number.',
    rules: [
      'Each player is assigned a number on the board.',
      'Hit your own number 5 times to become a Killer.',
      'Once a Killer, hit opponents’ numbers to remove their lives.',
      'Each player starts with 3 lives.',
      'Lose all your lives and you’re eliminated.',
      'Last player standing wins.',
    ] },
  'speed101': { start: 101, label: 'Speed 101', party: true,
    desc: 'Race to zero from 101 — fastest checkout wins. No double-out.',
    rules: [
      'Everyone starts on 101.',
      'Race to reach exactly zero.',
      'Straight Out only — no double required.',
      'First to check out wins the round.',
      'A party mode built for quick, chaotic fun.',
    ] },
  'highscore': { start: 0, label: 'High Score', party: true,
    desc: 'Score as much as you can in 7 visits. Highest total wins!',
    rules: [
      'No target score — pure scoring.',
      'Each player gets exactly 7 visits of 3 darts.',
      'Your total score across all 7 visits is your result.',
      'Highest total wins.',
      'A party mode for finding out who can really pile on the points.',
    ] },
  'battle': { start: 0, label: 'Battle', party: true,
    desc: 'Use your attributes! Each dart deals damage to an opponent. Last one standing wins.',
    rules: [
      'Each player starts with HP equal to their Health attribute (base 300, cap 500).',
      'Armor is a flat reduction applied to EVERY dart (base 0, cap 25).',
      'Power is a flat bonus added to EVERY dart that hits (base 0, cap 30).',
      'Each visit you attack one opponent — in 1v1 it is automatic.',
      'Per-dart damage = (dart value + power) − armor, min 1 on a hit.',
      'Misses deal 0 damage (power only applies on successful hits).',
      'Reduce an opponent to 0 HP to defeat them.',
      'Last player standing wins the battle.',
    ] },
};

export const MODE_KEYS = Object.keys(MODES);

export const ATC_TARGETS = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,'Bull'];
export const atcLabel = (i: number) => i >= ATC_TARGETS.length ? 'Done' : String(ATC_TARGETS[i]);

export const DARTBOARD_NUMBERS = [20,1,18,4,13,6,10,15,2,17,3,19,7,16,8,11,14,9,12,5];
