/*
# Create app_state and games tables for server-side sync

## Purpose
The dart-counter app previously stored all data in localStorage. This migration
moves shared data (players, settings, completed match history) to Supabase so
multiple users can see the same data across devices. No authentication is used
— the app is single-tenant with a few trusted users sharing one data namespace.

## Data flow
- In-progress matches (activeGame) stay in localStorage only, so multiple
  people can play simultaneously without overwriting each other's active game.
- Player data (roster, XP, level, unlocked titles) and app settings (including
  custom titles) sync to the `app_state` table.
- Completed match results sync to the `games` table — one row per finished game.

## New Tables

### app_state
Single-row table holding shared players and settings as JSONB.
- `id` (text, primary key, default 'main') — always 'main' for this single-tenant app
- `players` (jsonb, default '[]') — shared player roster with XP/level/titles
- `settings` (jsonb, default '{}') — shared app settings including custom titles
- `updated_at` (timestamptz) — last sync timestamp

### games
One row per completed match record.
- `id` (text, primary key) — matches GameRecord.id generated by the app
- `data` (jsonb) — full GameRecord object
- `created_at` (timestamptz) — when the row was inserted

## Security
- RLS enabled on both tables.
- Policies allow anon + authenticated full CRUD (TO anon, authenticated).
  This is intentional: the app has no login screen, so the anon-key client must
  be able to read and write. The data is intentionally shared across all users.

## Notes
1. The app_state row is created lazily — the first upsert from the client
   creates the 'main' row.
2. Games use a separate table (not a JSONB array) so concurrent INSERTs from
   different devices finishing matches simultaneously don't conflict.
3. Player XP conflicts are resolved client-side on merge: the higher XP/level
   wins (existing mergeBackup logic in the app).
*/

CREATE TABLE IF NOT EXISTS app_state (
  id text PRIMARY KEY DEFAULT 'main',
  players jsonb NOT NULL DEFAULT '[]'::jsonb,
  settings jsonb NOT NULL DEFAULT '{}'::jsonb,
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE app_state ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_app_state" ON app_state;
CREATE POLICY "anon_select_app_state" ON app_state FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "anon_insert_app_state" ON app_state;
CREATE POLICY "anon_insert_app_state" ON app_state FOR INSERT
  TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "anon_update_app_state" ON app_state;
CREATE POLICY "anon_update_app_state" ON app_state FOR UPDATE
  TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "anon_delete_app_state" ON app_state;
CREATE POLICY "anon_delete_app_state" ON app_state FOR DELETE
  TO anon, authenticated USING (true);

CREATE TABLE IF NOT EXISTS games (
  id text PRIMARY KEY,
  data jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE games ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_games" ON games;
CREATE POLICY "anon_select_games" ON games FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "anon_insert_games" ON games;
CREATE POLICY "anon_insert_games" ON games FOR INSERT
  TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "anon_update_games" ON games;
CREATE POLICY "anon_update_games" ON games FOR UPDATE
  TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "anon_delete_games" ON games;
CREATE POLICY "anon_delete_games" ON games FOR DELETE
  TO anon, authenticated USING (true);
